### ISSUE TITLE
Too few arguments to function

### ISSUE THREAD

**Issue by Xachman** [ivanamat/cakephp3-markdown#2]
got "Too few arguments to function Cake\Controller\Component::initialize(), 0 passed in " when using initialize example.

```
   public function initialize() {
        parent::initialize();

        $this->loadComponent('Markdown.Markdown');
    }
```

**Comment by Xachman** [comment]
This problem is a php 7 issue.  The MarkdownComponent needs to include all the parameters of the original Component class when using the initialize function.

**Comment by ivanamat** [comment]
Hi @Xachman!

Sorry for having been slow to respond. 
Thank you for reporting the bug!

This have been merged and solved! ;) https://github.com/ivanamat/cakephp3-markdown/pull/3

Regards!
