### ISSUE TITLE
On CakePHP 3.5 I get "Too few arguments to function Cake\Controller\Component::initialize()"

### ISSUE THREAD

**Issue by johnydeep100** [ivanamat/cakephp3-markdown#4]
Installed your package on a CakePHP 3.5 install (got it this week). It is fairly new, so no conflict with other packages is unlikely.

I installed this package today, with the instructions on repo home.
After I installed it, I got this:

```
Too few arguments to function Cake\Controller\Component::initialize(), 0 passed in /srv/http/cakephp1/vendor/ivanamat/cakephp3-markdown/src/Controller/Component/MarkdownComponent.php on line 37 and exactly 1 expected ArgumentCountError
```

I opened `/vendor/ivanamat/cakephp3-markdown/src/Controller/Component/MarkdownComponent.php` and the problem was with this line:
```
    public function initialize(){
        parent::initialize(); // <- this line
```

I added a blank array:

```
parent::initialize(array());
```

Then it was gone, but another error appeared at the top:
```
Warning (2): Declaration of Markdown\Controller\Component\MarkdownComponent::initialize() should be compatible with Cake\Controller\Component::initialize(array $config) [ROOT/vendor/ivanamat/cakephp3-markdown/src/Controller/Component/MarkdownComponent.php, line 54]
```

Then, to remedy this I added a `$config` variable:
```
public function initialize($config){
```

Please tell me how else I can solve this? Is there any way without editing the files in your package?

**Comment by ivanamat** [comment]
Hi @johnydeep100

It is solved in the master branch ( https://github.com/ivanamat/cakephp3-markdown/pull/3 ), I forgot to create a release!
Sorry, I'm going to create it now.

**Comment by ivanamat** [comment]
@johnydeep100 

New release 1.1 https://github.com/ivanamat/cakephp3-markdown/releases/tag/1.1
Please update the plugin and confirm that the issue has been solved.

Regards!

**Comment by johnydeep100** [comment]
I updated. It is now working without a problem. So it should be solved.
Thanks.
